name: MSBuild

on: workflow_dispatch

env:
  SOLUTION_FILE_PATH: TranslucentTB.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: MSBuild -m -p:"Configuration=${{env.BUILD_CONFIGURATION}};Platform=${{env.BUILD_PLATFORM}}" ${{env.SOLUTION_FILE_PATH}}

      - uses: actions/upload-artifact@v3
        with:
          path: ${{env.GITHUB_WORKSPACE}}
